coverage:
  ignore:
    - "custom_components/lifesmart/tests/**/*"  # 忽略 tests 目录下的所有文件
  status:
    project:
      default:
        informational: false
        target: 85%           # 目标覆盖率
    patch:
      default:
        informational: false
        target: 70%