name: '🐛 Bug Report'
description: 'Report a bug'
title: '[BUG] '
labels: [ '🔍 Unconfirmed' ]
body:
  - type: dropdown
    attributes:
      label: '📦 HomeAssistant Deployment'
      multiple: true
      options:
        - 'Docker'
        - 'Self hosting'
        - 'Cloud hosting'
        - 'Local/Router etc.'
        - 'Other'
    validations:
      required: true
  - type: input
    attributes:
      label: '📌 Version'
    validations:
      required: true
  - type: dropdown
    attributes:
      label: '🌐 Browser'
      multiple: true
      options:
        - 'Chrome'
        - 'Edge'
        - 'Safari'
        - 'Firefox'
        - 'Other'
    validations:
      required: true
  - type: textarea
    attributes:
      label: '🐛 Bug Description'
      description: A clear and concise description of the bug, if the above option is `Other`, please also explain in detail.
    validations:
      required: true
  - type: textarea
    attributes:
      label: '📷 Recurrence Steps'
      description: A clear and concise description of how to recurrence.
  - type: textarea
    attributes:
      label: '🚦 Expected Behavior'
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: '📝 Additional Information & Diagnostics'
      description: |
        **Please provide additional information about your issue:**
        
        If your problem needs further explanation, or if the issue you're seeing cannot be reproduced easily, please add more information here.
        
        **📊 Diagnostics Data (Highly Recommended):**
        To help us identify issues quickly, please upload the diagnostics file from Home Assistant:
        1. Go to Settings → Devices & Services → LifeSmart
        2. Click "Download diagnostics" button
        3. Upload the .json file here or paste the content
        
        For device-specific issues, you can also download device-level diagnostics:
        1. Go to Settings → Devices & Services → LifeSmart → [Select specific device]
        2. Click "Download diagnostics" for that device
        
        The diagnostics data contains comprehensive system information that helps us identify issues without requiring manual log collection.
