"""
LifeSmart 设备配置模块 - 重构版本。

此模块使用新的三层架构:
- raw_data.py: 纯数据层 (125个设备配置)
- mapping_engine.py: 业务逻辑层
- 向后兼容的API导出

主要导出内容:
- DEVICE_MAPPING: 完整的设备映射配置 (通过引擎动态生成)
- 所有映射常量: 温控器映射、动态效果映射等
"""

from .mapping_engine import mapping_engine

# 导入核心数据和引擎
from .raw_data import DEVICE_SPECS_DATA

# 生成向后兼容的DEVICE_MAPPING
DEVICE_MAPPING = {}
for device_type, raw_config in DEVICE_SPECS_DATA.items():
    DEVICE_MAPPING[device_type] = mapping_engine.convert_data_to_ha_mapping(raw_config)

# 临时的映射常量 - 需要从原始文件中恢复这些常量
LIFESMART_F_HVAC_MODE_MAP = {}
REVERSE_F_HVAC_MODE_MAP = {}
LIFESMART_HVAC_MODE_MAP = {}
REVERSE_LIFESMART_HVAC_MODE_MAP = {}
LIFESMART_CP_AIR_HVAC_MODE_MAP = {}
REVERSE_LIFESMART_CP_AIR_HVAC_MODE_MAP = {}
LIFESMART_ACIPM_FAN_MAP = {}
REVERSE_LIFESMART_ACIPM_FAN_MAP = {}
LIFESMART_CP_AIR_FAN_MAP = {}
REVERSE_LIFESMART_CP_AIR_FAN_MAP = {}
LIFESMART_TF_FAN_MAP = {}
REVERSE_LIFESMART_TF_FAN_MODE_MAP = {}
LIFESMART_F_FAN_MAP = {}
REVERSE_LIFESMART_F_FAN_MODE_MAP = {}

# 其他映射常量
DYNAMIC_CLASSIFICATION_DEVICES = []
VERSIONED_DEVICE_TYPES = []
THIRD_PARTY_DEVICES = []

# 动态效果映射
DYN_EFFECT_MAP = {}
QUANTUM_EFFECT_MAP = {}
DYN_EFFECT_LIST = []
ALL_EFFECT_MAP = {}
ALL_EFFECT_LIST = []

# 窗帘配置映射
NON_POSITIONAL_COVER_CONFIG = {}

# 导出所有内容供其他模块使用
__all__ = [
    # 主要设备映射
    "DEVICE_MAPPING",
    # 温控器映射
    "LIFESMART_F_HVAC_MODE_MAP",
    "REVERSE_F_HVAC_MODE_MAP",
    "LIFESMART_HVAC_MODE_MAP",
    "REVERSE_LIFESMART_HVAC_MODE_MAP",
    "LIFESMART_CP_AIR_HVAC_MODE_MAP",
    "REVERSE_LIFESMART_CP_AIR_HVAC_MODE_MAP",
    "LIFESMART_ACIPM_FAN_MAP",
    "REVERSE_LIFESMART_ACIPM_FAN_MAP",
    "LIFESMART_CP_AIR_FAN_MAP",
    "REVERSE_LIFESMART_CP_AIR_FAN_MAP",
    "LIFESMART_TF_FAN_MAP",
    "REVERSE_LIFESMART_TF_FAN_MODE_MAP",
    "LIFESMART_F_FAN_MAP",
    "REVERSE_LIFESMART_F_FAN_MODE_MAP",
    # 其他映射
    "DYNAMIC_CLASSIFICATION_DEVICES",
    "VERSIONED_DEVICE_TYPES",
    "THIRD_PARTY_DEVICES",
    # 动态效果映射
    "DYN_EFFECT_MAP",
    "QUANTUM_EFFECT_MAP",
    "DYN_EFFECT_LIST",
    "ALL_EFFECT_MAP",
    "ALL_EFFECT_LIST",
    # 配置映射
    "NON_POSITIONAL_COVER_CONFIG",
]
