name: LS Union Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:  # 允许手动触发

jobs:
  test:
    name: "LifeSmart Unit/Union Tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # 测试四个关键版本：使用pytest插件实际支持的HA版本
        homeassistant-version: [ "2023.6.0", "2024.2.0", "2024.12.0", "latest" ]
        include:
          - homeassistant-version: "2023.6.0"
            python-version: "3.11"  # Python 3.11全面支持
          - homeassistant-version: "2024.2.0"
            python-version: "3.12"  # Python 3.12全面支持
          - homeassistant-version: "2024.12.0"
            python-version: "3.13"  # Python 3.13全面支持
          - homeassistant-version: "latest"
            python-version: "3.13"  # 最新版本

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          # 根据HA版本安装兼容的pytest-homeassistant-custom-component版本
          # pytest-homeassistant-custom-component插件会自动安装pytest和HA
          # 为Python 3.11应用PEP 517解决方案解决lru-dict编译问题
          if [[ "${{ matrix.homeassistant-version }}" == "2023.6.0" ]]; then
            # HA 2023.6.0 - 使用插件 0.13.36 (自动安装pytest和HA)  
            pip install "pytest-homeassistant-custom-component==0.13.36"
          elif [[ "${{ matrix.homeassistant-version }}" == "2024.2.0" ]]; then
            # HA 2024.2.0 - 使用插件 0.13.99 (自动安装pytest和HA)
            pip install "pytest-homeassistant-custom-component==0.13.99"
          elif [[ "${{ matrix.homeassistant-version }}" == "2024.12.0" ]]; then
            # HA 2024.12.0 - 使用插件 0.13.190 (自动安装pytest和HA)
            pip install "pytest-homeassistant-custom-component==0.13.190"
          elif [[ "${{ matrix.homeassistant-version }}" == "latest" ]]; then
            # HA 最新 - 使用最新插件 (自动安装pytest和HA)
            pip install "pytest-homeassistant-custom-component"
          else
            # 回退到通用版本
            pip install pytest-homeassistant-custom-component
          fi
          
          # 安装其他测试依赖
          pip install flake8

      - name: Run Flake8 Lint
        run: |
          flake8 --count --show-source --statistics custom_components/lifesmart

      - name: Run unit tests with pytest (HA ${{ matrix.homeassistant-version }})
        env:
          PYTHONPATH: .
        run: |
          # 对于其他HA版本，使用标准配置
          pytest \
            -v \
            --cov \
            --cov-branch \
            --cov-report=xml \
            --junitxml=junit-${{ matrix.homeassistant-version }}.xml -o junit_family=legacy

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}