name: LS Union Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "LifeSmart Unit/Union Tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12" ]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov pytest-homeassistant-custom-component flake8

      - name: Run Flake8 Lint
        run: |
          flake8 --count --show-source --statistics custom_components/lifesmart

      - name: Run unit tests with pytest
        env:
          PYTHONPATH: .
        run: |
          pytest \
            -v \
            --cov \
            --cov-branch \
            --cov-report=xml \
            --junitxml=junit.xml -o junit_family=legacy

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}