name: Run Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "Run LifeSmart Unit Tests"
    runs-on: ubuntu-latest


    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov pytest-homeassistant-custom-component

      - name: Run unit tests with pytest
        working-directory: ./custom_components/lifesmart
        run: |
          pytest -v -m github -c tests/pytest.ini tests/ --cov --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
