name: Run Union Tests CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: "LifeSmart Unit/Union Tests"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11", "3.12" ] # 根据HA支持的版本调整


    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio pytest-cov pytest-homeassistant-custom-component

      - name: Run unit tests with pytest
        env:
          PYTHONPATH: .
        run: |
          pytest \
            -v \
            -c "custom_components/lifesmart/tests/pytest.ini" \
            "custom_components/lifesmart/tests/" \
            --cov=custom_components.lifesmart \
            --cov-branch \
            --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
